# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RealmSwift'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Charts'
  # Pods for project

end
